### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Hum4n01d** [vkurchatkin/quartz-display-services#1]
I can't install your package; I'm getting this error:

```
    display_arr -> Set(i, Integer::NewFromUnsigned(displays[i]));
                          ~~~~~~~~~~~~~~~~~~~~~~~~            ^
/Users/Hum4n01d/.node-gyp/6.9.4/include/node/v8.h:2559:3: note: 'NewFromUnsigned' declared here
  static Local<Integer> NewFromUnsigned(Isolate* isolate, uint32_t value);
  ^
../src/quartz_display_services.cc:64:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(display_arr);
         ~~~~~ ^
../src/quartz_display_services.cc:67:1: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'
?
DEFINE_BOOLEAN_METHOD (DisplayIsActive)
^
../src/quartz_display_services.cc:5:64: note: expanded from macro 'DEFINE_BOOLEAN_METHOD'
#define DEFINE_BOOLEAN_METHOD(name) Handle <Value> name (const Arguments& args) { \
                                                               ^
/Users/Hum4n01d/.node-gyp/6.9.4/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/quartz_display_services.cc:67:1: error: calling a protected constructor of class 'v8::HandleScope'
DEFINE_BOOLEAN_METHOD (DisplayIsActive)
^
../src/quartz_display_services.cc:6:15: note: expanded from macro 'DEFINE_BOOLEAN_METHOD'
  HandleScope scope; \
              ^
/Users/Hum4n01d/.node-gyp/6.9.4/include/node/v8.h:915:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/quartz_display_services.cc:67:1: error: type 'const v8::internal::Arguments' does not provide a subscript ope
rator
DEFINE_BOOLEAN_METHOD (DisplayIsActive)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/quartz_display_services.cc:7:57: note: expanded from macro 'DEFINE_BOOLEAN_METHOD'
  CGDirectDisplayID displayId = (CGDirectDisplayID) args[0] -> Uint32Value(); \
                                                    ~~~~^~
../src/quartz_display_services.cc:67:1: error: no member named 'Close' in 'v8::HandleScope'
DEFINE_BOOLEAN_METHOD (DisplayIsActive)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/quartz_display_services.cc:8:16: note: expanded from macro 'DEFINE_BOOLEAN_METHOD'
  return scope.Close(v8::Boolean::New(CG ## name (displayId))); \
         ~~~~~ ^
../src/quartz_display_services.cc:67:1: error: too few arguments to function call, expected 2, have 1
DEFINE_BOOLEAN_METHOD (DisplayIsActive)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/quartz_display_services.cc:8:61: note: expanded from macro 'DEFINE_BOOLEAN_METHOD'
  return scope.Close(v8::Boolean::New(CG ## name (displayId))); \
                     ~~~~~~~~~~~~~~~~                       ^
/Users/Hum4n01d/.node-gyp/6.9.4/include/node/v8.h:8000:1: note: 'New' declared here
Local<Boolean> Boolean::New(Isolate* isolate, bool value) {
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/quartz_display_services/src/quartz_display_services.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Hum4n01d/.yarn/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/Hum4n01d/.yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
```

**Comment by Hum4n01d** [comment]
Never mind, I tried again and it worked! Who knows what happened.

**Comment by Hum4n01d** [comment]
Ok, well actually after the bindings failed I was able to install the package, but when I tried to use it I got this error: 

```
/Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/build/quartz_display_services.no
de
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/build/Debug/quartz_display_servi
ces.node
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/build/Release/quartz_display_ser
vices.node
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/out/Debug/quartz_display_service
s.node
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/Debug/quartz_display_services.no
de
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/out/Release/quartz_display_servi
ces.node
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/Release/quartz_display_services.
node
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/build/default/quartz_display_ser
vices.node
 → /Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/compiled/6.9.4/darwin/x64/quartz
_display_services.node
    at bindings (/Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/node_modules/quartz-display-services/index.js
:1:91)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Hum4n01d/Desktop/Tech/Node/AddToPlaylist/index.js:2:18)
```

**Comment by vkurchatkin** [comment]
This thing is just too old, probably tested on node 0.10, or something like that

**Comment by Hum4n01d** [comment]
Ok
